Add wake up text based on laziness, fix some typos, fix name capitalization
Ecialo/mauricio pull request #15
Opened 2020-04-07 14:42 UTC by FrolovAlexandr

2020-04-07 15:26 UTC, Ecialo requested changes

2020-04-07 15:26 UTC, Ecialo commented on test/cat/state/sleep_test.exs
> +    expected = Text.get_all_texts(:wake_up_lazy, who: member, cat: cat)
Добавь пожалуйста, ещё тест на ветку с просыпанием неленивого котика. Хочется защититься от возможных ошибок в шаблонах внутри текстов :о)

2020-04-07 15:26 UTC, Ecialo commented
И спасибо за работу!

2020-04-07 17:20 UTC, Ecialo commented on test/cat/state/sleep_test.exs
> +    expected = Text.get_all_texts(:wake_up_lazy, who: member, cat: cat)
Спасибо!

2020-04-07 17:29 UTC, Ecialo requested changes
После этой правки я с радостью волью изменения :о)

2020-04-07 17:29 UTC, Ecialo commented on test/cat/state/sleep_test.exs
> +    Helpers.test_cat_falling_asleep(thin_cat, member)
Мне нравится идея с функцией :о) Давай только перетащим её определение из хэлперов, где всё-таки чуть более общие вещи прямо в модуль с тестом.

2020-04-07 17:48 UTC, FrolovAlexandr commented on test/cat/state/sleep_test.exs
> +    Helpers.test_cat_falling_asleep(thin_cat, member)
я чот затупил)))))))))))))))00000000000000000000

2020-04-08 12:47 UTC, Ecialo approved these changes

2020-04-08 12:47 UTC, merged

2020-04-08 12:47 UTC, Ecialo commented
Ещё раз спасибо за работу!