Take only needed fields from Nadia.Model.Update struct during update handle
Ecialo/mauricio pull request #28
Opened 2020-06-07 11:22 UTC by anime-memes

Fixes #27

2020-06-07 11:23 UTC, anime-memes commented
В первом коммите изменения про доставание нужных полей из структуры апдейта, в остальных - форматирование и всё такое

2020-06-08 07:51 UTC, Ecialo requested changes
Спасибо за работу!

Есть ещё одна маленькая просьба: попробуй замерить выйграли ли мы что-нибудь в плане производительности от этих изменений. Судя по докам, что приводил в тикете должны, но проверить не повредит. Заодно посмотрим насколько. Benchee вроде бы должен тебе помочь в этом

2020-06-08 07:51 UTC, Ecialo commented on config/config.exs
> +      "ХррХррр"
Если есть возможность, то давай не будем убирать замыкающую запятую из коллекций. Она не стоит ничего, но чуть упрощает редактирование подобных коллекций, т.к. они становятся единообразно заполнены.

2020-06-08 07:51 UTC, Ecialo commented on lib/mauricio/acceptor.ex
> +    |> call_process_update()
В отладке бота используется poll режим. Пожалуйста подключи эту же распаковку к poller-у, чтобы мы могли спокойно отлаживаться.

2020-06-08 07:51 UTC, Ecialo commented on lib/mauricio/catchat/chat.ex
> +  @spec process_message(map(), Chat.state()) :: Chat.state()
Заведи, пожалуйста, отдельный тип под новую распакованную структуру. Это поможет dialyzer-у следить что мы не ходим не в те поля, ну и в целом улучшит понимание.

2020-06-08 07:51 UTC, Ecialo commented on test/test_helper.exs
> -    %NadiaUpdate{
Давай не будет удалять хэлперы для сырых сообщений из телеги. Они ещё пригодятся как минимум для поддержки логики распаковки.

2020-06-16 19:57 UTC, eveningsteps commented on config/config.exs
> +      "ХррХррр"
а можно credo этому научить?

2020-06-16 20:06 UTC, anime-memes commented on config/config.exs
> +      "ХррХррр"
это не credo, это результат `mix format`. я посмотрел опции и не похоже, что можно добавить https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-formatting-options

2020-06-16 21:51 UTC, Ecialo commented on config/config.exs
> +      "ХррХррр"
Ну тогда чёрт с ней

2020-06-22 10:38 UTC, anime-memes commented on benchmarks/nadia_vs_map.exs
> +Benchee.run(
Последний результат у меня на ноуте:
```
Name                   ips        average  deviation         median         99th %
Map update          9.23 M      108.32 ns ±21273.36%          65 ns         251 ns
Nadia update        8.30 M      120.47 ns ±19350.30%          72 ns         223 ns

Comparison: 
Map update          9.23 M
Nadia update        8.30 M - 1.11x slower +12.16 ns

Memory usage statistics:

Name            Memory usage
Map update             104 B
Nadia update           104 B - 1.00x memory usage +0 B
```
Результаты нестабильны, два запуска подряд могут показать, что сначала мапа быстрее, а потом медленее.
Я ничего не понимаю и буду признателен, если мне скажут, где я проебался.

2020-06-22 14:21 UTC, Ecialo commented on benchmarks/nadia_vs_map.exs
> +Benchee.run(
Саня, давай попробуем замерить только копирование при пересылке. Меня в основном интересует только оно. У тебя сейчас идёт очень много cast запросов с операциями, которые кушают процессор, но кмк не очень интересны. Elixir [не гарантирует](https://hexdocs.pm/elixir/GenServer.html#cast/2) порядок их обработки и у меня есть подозрения, что иногда оно не выполняет все эти замены текста, а иногда выполняет и мы ждём в call их отработки. И отсюда такой разброс (в 1000 раз больше, чем в примерах на странице benchee)

Предлагаю просто слать самому себе сообщение и тут же его вычитывать. Тогда, по идее, мы посмотрим только на копирование структуры. Если там будет какой-то абсурд и ерланг оптимизирует такие посылки, то мы во первых про это узнаем, что само по себе круто, а во вторых просто перепишем на пересылку в другой процесс, можно и ген сервера.

2020-06-28 22:30 UTC, Ecialo commented
Спасибо за работу!

2020-06-28 22:30 UTC, merged