Long live storage
Ecialo/mauricio pull request #31
Opened 2020-06-15 10:21 UTC by Ecialo

Что поменял:
* В `mauricio.ex` добавил логику выбора типа хранилища. Сейчас на выбор либо словари (как раньше) либо монга
* Поменял конфиги, чтобы из них можно было брать тип хранилища
* В `catchat.ex` добавил что после старта идём в хранилище и вытаскиваем все id чатов, и стартуем их
* В `storage/serializable ` добавил протокол `Serializable` реализация которого позволяет кодировать типы эликсира с форматом монги.
* В `storage/decoder` декодирования из монги
* В `storage/mongo_storage` реализация сохранений-загрузок в-из монги
* Добавил `test/test_data/test_data.ex` c моделями PropCheck и начал их использовать в тестах
* Прогнал форматтер на части кода и добавил кое-где доктестов

Должно закрыть #3 и #11

2020-06-16 19:40 UTC, ghost requested changes
замечаний по сути у меня нет, работаю линтером.
ps а твой сериализатор сможет сохранить в монгу вложенную `Map`?

2020-06-16 19:40 UTC, eveningsteps commented on lib/mauricio.ex
> +      _anything_else ->
а почему не просто `_`?

2020-06-16 19:40 UTC, eveningsteps commented on lib/mauricio/storage/mongo_storage.ex
> +      Mongo.find(storage, @coll, %{}, projection: %{"chat_id" => 1, "_id" => 0})
ты не хочешь тут вместо строк сделать атрибуты типа `@chat_id` и `@_id`?

2020-06-16 19:40 UTC, eveningsteps commented on lib/mauricio/storage/serializable.ex
> +  How to simplify data to fromats allowed by mongodb. Shipped with this:
`formats` же

2020-06-16 19:40 UTC, eveningsteps commented on test/cat_test.exs
> +      cat ==
`assert cat == ...`?

2020-06-16 19:40 UTC, eveningsteps commented on test/chat_test.exs
> +      chat ==
`assert chat == ...`?

2020-06-16 19:40 UTC, eveningsteps commented on test/member_test.exs
> +      member ==
`assert member == ...`?

2020-06-16 19:40 UTC, eveningsteps commented on test/storage/serialization_test.exs
> +end
а как это работает?

2020-06-16 20:11 UTC, Ecialo commented
> замечаний по сути у меня нет, работаю линтером.
> ps а твой сериализатор сможет сохранить в монгу вложенную `Map`?

Он уже сохраняет `%{user_id =`Member}`

2020-06-16 20:34 UTC, Ecialo commented on lib/mauricio/storage/mongo_storage.ex
> +      Mongo.find(storage, @coll, %{}, projection: %{"chat_id" => 1, "_id" => 0})
Можно попробовать

2020-06-16 20:35 UTC, Ecialo commented on lib/mauricio.ex
> +      _anything_else ->
Захотелось. Никакой другой мотивации.

2020-06-16 20:36 UTC, Ecialo commented on lib/mauricio/storage/serializable.ex
> +  How to simplify data to fromats allowed by mongodb. Shipped with this:
Поправлю >_>

2020-06-16 20:38 UTC, Ecialo commented
Мне очень важно чтобы вы посмотрели нет ли какой-то очевидной проблемы, в последовательности загрузки состояний чатов на старте-рестарте. У меня пока я писал очень глаз замылился :о(

2020-06-17 09:49 UTC, Ecialo commented on test/storage/serialization_test.exs
> +end
[doctest](https://hexdocs.pm/ex_unit/ExUnit.DocTest.html#doctest/2)

2020-06-23 13:24 UTC, Ecialo commented
На всякий случай для истории. Мы тут ждём пока наш весёлый-девопс @Preveter восстановит пред прод, который гигаликсир зарезал до 0 реплик из-за неактивности, чтобы при вливании ветки в мастер код про базу автоматически на него выехал.

2020-06-25 17:24 UTC, merged