Random cat names
Ecialo/mauricio pull request #40
Opened 2020-07-27 19:53 UTC by anime-memes

Описано в #33. Во всех шаблонах, где есть какое-то подлежащее про кота, вызывается функция, возвращающая рандомную кличку из пула или реальное имя котика (вероятность - параметр в конфиге); в аргументах передаётся нынешнее окружение для упрощения тестов. У падежей разный пул слов из-за того, что прилагательные тоже склоняются по падежам и всё ломается

2020-07-29 07:22 UTC, Ecialo requested changes
Спасибо за работу! Поправь, пожалуйста, по замечаниям. Ещё кодков пишет, что упало покрытие. Там ничего критичного, но будет хорошо если это тоже поправишь.

2020-07-29 07:22 UTC, Ecialo commented on config/dev.exs
> +  env: :dev
Зачем это? Ну т.е. у нас же уже эти конфиги подставляются на основе переменной окружения с ровно таким же содержанием.

2020-07-29 07:22 UTC, Ecialo commented on config/config.exs
> +      "<i><%= CatName.fetch(:nominative, true, cat.name, Application.get_env(:mauricio, :env)) %> сладко уснул на диване, выставив теплое пузико напоказ.</i>",
Слишком сложная схема вызова для шаблона, пользоваться ею будет очень изнурительно. Я не понимаю зачем нужен третий параметр, да и правила на простановку заглавной буквы не настолько сложные чтобы выделять  на это отдельный флаг. Предлагаю примерно такую сигнатуру `CatName.in(:nominative)`  или `Cat.name_in(:nominative)`.

2020-07-29 07:22 UTC, Ecialo commented on config/config.exs
> +    <i>У вас завелся <%= CatName.fetch(:nominative, false, Application.get_env(:mauricio, :env)) %>. Сейчас он тихо сидит в уголке.
В этот момент имени кота ещё не существует. Что будет если оно вытянется?

2020-07-29 07:22 UTC, Ecialo commented on test/text_test.exs
> +
Давай добавим ещё тест, что вытянув 1000 (или больше) раз случайное именование кота мы получим полный набор его позывных из конфига.

2020-07-29 07:42 UTC, anime-memes commented on config/config.exs
> +    <i>У вас завелся <%= CatName.fetch(:nominative, false, Application.get_env(:mauricio, :env)) %>. Сейчас он тихо сидит в уголке.
Оно не вытянется, если не передан `cat.name`. Есть больше одного места, где нельзя достать имя кота, поэтому две функции используется - одна там, где можно (выбирается либо настоящее имя кота, либо что-то из конфига), вторая там, где нельзя (выбирается только что-то из конфига)

2020-07-29 07:47 UTC, anime-memes commented on config/config.exs
> +      "<i><%= CatName.fetch(:nominative, true, cat.name, Application.get_env(:mauricio, :env)) %> сладко уснул на диване, выставив теплое пузико напоказ.</i>",
Нам всё равно надо как-то указать, что мы хотим увидеть имя с заглавной буквой, потому что нельзя просто делать заглавную букву тогда, когда запрашивается именительный падеж (есть места, где нужен именительный падеж в середине предложения и "у вас завёлся Котик" будет выглядеть странно). Можно так - `Cat.name_in(:nominative)` и `Cat.capitalized_name_in(:nominative)`

2020-07-29 07:53 UTC, anime-memes commented on config/dev.exs
> +  env: :dev
Чтобы отдавать имя в зависимости от окружения (я не придумал более хороший способ починки тестов, а `Mix.env()` недоступен в рантайме и не получится различать внутри функции)

2020-07-29 07:54 UTC, anime-memes commented
Кодков показывается на файл, который я вообще не трогал. Не очень понимаю, что от меня требуется

2020-07-29 08:09 UTC, anime-memes commented on test/text_test.exs
> +
Это не гарантируется же. Или ты хочешь, чтобы гарантировалось?

2020-07-29 15:54 UTC, Ecialo commented on config/config.exs
> +      "<i><%= CatName.fetch(:nominative, true, cat.name, Application.get_env(:mauricio, :env)) %> сладко уснул на диване, выставив теплое пузико напоказ.</i>",
Насколько я понимаю, заглавная буква бывает в имени (оно и так всегда с заглавной), либо после точки. Информация о точке есть в тексте сообщения. Можно подумать как её оттуда извлечь. Твой вариант тоже вполне хорош :о)

2020-07-29 15:55 UTC, Ecialo commented on config/config.exs
> +    <i>У вас завелся <%= CatName.fetch(:nominative, false, Application.get_env(:mauricio, :env)) %>. Сейчас он тихо сидит в уголке.
Рад что ты это предусмотрел \:оD/

2020-07-29 15:57 UTC, Ecialo commented on test/text_test.exs
> +
Я хочу, чтобы был тест на то, что все погоняла из тех что перечислены в конфиге могут встретиться. Если мы захотим поменять логику выбора погоняла, этот тест будет очень кстати.

2020-07-29 15:58 UTC, Ecialo commented
> Кодков показывается на файл, который я вообще не трогал. Не очень понимаю, что от меня требуется

Тогда забей :о)

2020-07-29 15:59 UTC, anime-memes commented on config/config.exs
> +      "<i><%= CatName.fetch(:nominative, true, cat.name, Application.get_env(:mauricio, :env)) %> сладко уснул на диване, выставив теплое пузико напоказ.</i>",
Сделал через две функции

2020-07-29 16:01 UTC, anime-memes commented on test/text_test.exs
> +
Добавил тест, погонял руками просто - нормально; потом попробовал прогнать этот тест 1000 раз - зафейлилось только тогда, когда понизил количество вытягиваний, так что возможно я преждевременно запаниковал по поводу того, что этот тест может фейлится просто так

2020-07-30 13:53 UTC, anime-memes commented
Почему оставил передавание имени кота в функцию: 1) есть несколько мест, где в шаблоне доступен сам кот вместе с именем, но мы не хотим его использовать (например, `Котику нравится имя Ярополк`); 2) точно так же в шаблоне используется функция `Member.full_name/1`

2020-08-08 17:32 UTC, merged

2020-08-08 17:32 UTC, Ecialo commented
Спасибо за работу!